mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('video/', include('video.urls')),
    path('admin/', admin.site.urls),
]

video/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'video'
urlpatterns = [
    path('', views.index, name='index'),
]

video/models.py
from django.db import models

class VideoContent(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    upload_date = models.DateTimeField()
    original_name = models.CharField(max_length=200)
    filename = models.CharField(max_length=200, default="")
    thumb_frame = models.IntegerField(default=0)

class VideoTagName(models.Model):
    name = models.CharField(max_length=200, default="")

class VideoTagList(models.Model):
    content = models.ForeignKey(VideoContent, on_delete=models.CASCADE)
    tag = models.ForeignKey(VideoTagName, on_delete=models.CASCADE)

video/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

def index(request):
    return render(request, 'video/index.html')

video/templates/video/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="robots" content="noindex,nofollow">
  <meta http-equiv="Pragma" Content="no-cache">
  <meta http-equiv="Cache-Control" Content="no-cache">
  <title>{% block title %}Video Manager{% endblock %}</title>
{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'video/main.css' %}">
{% block header %}{% endblock %}
</head>
<body>

<h1><a href="{% url 'video:index' %}">Video Service</a></h1>
{% block main %}

{% endblock %}
</body>
</html>

video/templates/video/index.html
{% extends "video/base.html" %}
{% block main %}
Hello, World
{% endblock %}